server:
  port: 8080

application:
  title: Person Registry System
  version: 1.0.0

spring:
  application:
    name: person-registry

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=person_db;encrypt=true;trustServerCertificate=true;
    username: sa
    password: Alma1234

  sql:
    init:
      mode: never

  jpa:
    hibernate:
      ddl-auto: none

    show-sql: false